# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('track', models.CharField(choices=[('24', '24'), ('26', '26'), ('27.5', '27.5'), ('29', '29')], max_length=4)),
                ('color', models.CharField(max_length=10)),
                ('year', models.CharField(blank=True, choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=4)),
            ],
            options={
                'verbose_name': 'Bicycle',
                'verbose_name_plural': 'Bicycles',
            },
        ),
    ]
