# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bicycle',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
