# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0002_auto_20160414_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='latitude',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='longitude',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
