# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0004_auto_20160414_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15),
        ),
    ]
